var menu_button = document.querySelector('.menu-button')
var menu = document.querySelector('.menu')
var slogan = document.querySelector('.slogan')
var link = document.querySelector('.link')
var cards = document.querySelector('.cards')
var redes = document.querySelector('.redes-sociais')
var footer = document.querySelector('.footer')

menu_button.addEventListener('click', function(){
    menu.classList.toggle('show-menu')
    slogan.classList.toggle('slogan-hidden')
    link.classList.toggle('link-hidden')
    cards.classList.toggle('cards-hidden')
    redes.classList.toggle('redes-hidden')
    footer.classList.toggle('footer-hidden')
})